version: '3'

services:
  scry-frontend:
    image: node:10
    user: node
    working_dir: /home/node/scry-frontend
    restart: always
    # app currently doesn't take environment variables for configuration
    # environment:
    #   ENV: dev
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/scry-frontend
    command: sh -c "yarn --no-progress --non-interactive && yarn start --no-progress --non-interactive"
